### ISSUE TITLE
Remove language parameter from link to mozilla.org 

### ISSUE THREAD

**Issue by anewuser** [Niamor/tabdownloads#2]
Update the link on the project description page, so that the Mozilla website will open in the user's preferred language:

https://addons.mozilla.org/en-US/firefox/addon/downloads-in-a-tab/ → https://addons.mozilla.org/firefox/addon/downloads-in-a-tab/

**Comment by Niamor** [comment]
Oh wow I'm so sorry, I never saw your message.
Thank you so much I changed it.
